import { Hashtag, Platform } from "@/types";

// Hashtag database organized by niche categories
// Each niche has tags with metadata for scoring and classification

interface NicheEntry {
  keywords: string[];
  tags: Omit<Hashtag, "score" | "category" | "competition">[];
  expansions: string[];
}

const nicheDatabase: Record<string, NicheEntry> = {
  fitness: {
    keywords: ["fitness", "gym", "workout", "exercise", "fit", "training", "bodybuilding", "weightlifting", "crossfit", "cardio"],
    tags: [
      { tag: "fitness", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "gym", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "workout", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "fitnessmotivation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "gymlife", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "fitfam", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "bodybuilding", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "weightlossjourney", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "healthylifestyle", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "nutrition", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "personaltrainer", platform: ["instagram"], volume: "medium" },
      { tag: "hiit", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "yoga", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "cardio", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "strengthtraining", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "homeworkout", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "fatloss", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "musclebuilding", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "running", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "planks", platform: ["instagram", "tiktok"], volume: "low" },
      { tag: "squatchallenge", platform: ["tiktok", "instagram"], volume: "medium" },
      { tag: "gymmotivation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "physique", platform: ["instagram"], volume: "low" },
      { tag: "fitnesstips", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "exerciseroutine", platform: ["youtube", "tiktok"], volume: "medium" },
      { tag: "flexibility", platform: ["instagram", "youtube"], volume: "low" },
      { tag: "transformation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "coreworkout", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "legday", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "shoulderworkout", platform: ["instagram", "youtube"], volume: "low" },
    ],
    expansions: ["exercise", "training", "weightlifting", "cardio", "strength", "endurance", "mobility", "wellness", "active", "health"],
  },
  running: {
    keywords: ["running", "marathon", "run", "jogging", "sprint", "trailrun"],
    tags: [
      { tag: "running", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "marathon", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "runnersofinstagram", platform: ["instagram"], volume: "high" },
      { tag: "runner", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "runningmotivation", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "marathontraining", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "runninglife", platform: ["instagram"], volume: "medium" },
      { tag: "runnerscommunity", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "trailrunning", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "ultramarathon", platform: ["instagram", "youtube"], volume: "low" },
      { tag: "runningtips", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "runclub", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "halfmarathon", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "runninggear", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "pace", platform: ["instagram"], volume: "low" },
      { tag: "runningform", platform: ["youtube", "tiktok"], volume: "low" },
      { tag: "morningrun", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "runstreak", platform: ["instagram"], volume: "low" },
      { tag: "5krun", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "10krun", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "runchallenge", platform: ["instagram", "tiktok"], volume: "medium" },
    ],
    expansions: ["endurance", "cardio", "fitness", "speed", "race", "jog", "sprint", "trail", "track", "stamina"],
  },
  investment: {
    keywords: ["investasi", "saham", "investing", "stock", "trading", "finance", "wealth", "crypto", "forex"],
    tags: [
      { tag: "investasi", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "investing", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "saham", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "stockmarket", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "financialfreedom", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "investor", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "wealth", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "crypto", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "trading", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "finance", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "bitcoin", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "forex", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "passiveincome", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "dividen", platform: ["instagram"], volume: "medium" },
      { tag: "reksadana", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "financialliteracy", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "investasipemula", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "cryptocurrency", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "earnmoney", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "financialgoals", platform: ["instagram"], volume: "medium" },
      { tag: "stocktips", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "investingforbeginners", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "sahamindonesia", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "belajarinvestasi", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "investmenttips", platform: ["instagram", "youtube"], volume: "medium" },
    ],
    expansions: ["money", "wealth", "finance", "trading", "economy", "profit", "asset", "portfolio", "capital", "market"],
  },
  travel: {
    keywords: ["travel", "trip", "holiday", "vacation", "wanderlust", "backpacking", "tourism", "explore"],
    tags: [
      { tag: "travel", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "wanderlust", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "travelgram", platform: ["instagram"], volume: "high" },
      { tag: "trip", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "explore", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "adventure", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "vacation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "holiday", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "backpacking", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "solotravel", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "travelphotography", platform: ["instagram"], volume: "high" },
      { tag: "roadtrip", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "nature", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "beach", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "mountains", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "travelblogger", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "travelguide", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "hiddengems", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "travelreels", platform: ["instagram"], volume: "high" },
      { tag: "budgettravel", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["explore", "adventure", "nature", "culture", "destination", "journey", "tourism", "getaway", "excursion", "expedition"],
  },
  food: {
    keywords: ["food", "cooking", "recipe", "makanan", "masakan", "kuliner", "baking", "delicious"],
    tags: [
      { tag: "food", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "foodie", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "cooking", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "recipe", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "delicious", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "homemade", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "baking", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "instafood", platform: ["instagram"], volume: "high" },
      { tag: "foodphotography", platform: ["instagram"], volume: "medium" },
      { tag: "yummy", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "healthyfood", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "comfortfood", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "dinner", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "breakfast", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "lunch", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "foodblogger", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "easyrecipe", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "vegetarian", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "vegan", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "chef", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "kuliner", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "masakanrumahan", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "makananenak", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "resepmasakan", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["cuisine", "gourmet", "taste", "flavor", "ingredient", "kitchen", "mealprep", "snack", "dessert", "appetizer"],
  },
  technology: {
    keywords: ["tech", "technology", "gadget", "digital", "coding", "programming", "software", "ai", "artificialintelligence", "startup"],
    tags: [
      { tag: "technology", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "tech", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "coding", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "programming", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "developer", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "ai", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "artificialintelligence", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "startup", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "gadget", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "innovation", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "software", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "webdev", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "machinelearning", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "cybersecurity", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "robotics", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "technews", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "programmingmemes", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "devlife", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "opensource", platform: ["instagram", "youtube"], volume: "low" },
      { tag: "javascript", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "python", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "reactjs", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["digital", "innovation", "software", "hardware", "future", "smart", "automation", "data", "cloud", "blockchain"],
  },
  fashion: {
    keywords: ["fashion", "style", "outfit", "ootd", "fashionista", "streetwear", "vintage", "modestfashion"],
    tags: [
      { tag: "fashion", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "style", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "ootd", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "outfit", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "fashionblogger", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "streetwear", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "modestfashion", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "vintage", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "fashioninspo", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "grwm", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "outfitideas", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "fashionista", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "sneakers", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "luxury", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "shopaholic", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "styleinspo", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "fashiontrends", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "wardrobe", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "thrift", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "hijabfashion", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "hijabstyle", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "muslimahfashion", platform: ["instagram", "tiktok"], volume: "medium" },
    ],
    expansions: ["trend", "wardrobe", "apparel", "couture", "accessories", "jewelry", "handbag", "shoe", "dress", "tailor"],
  },
  photography: {
    keywords: ["photography", "photo", "photoshoot", "camera", "photographer", "portrait", "landscape"],
    tags: [
      { tag: "photography", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "photooftheday", platform: ["instagram"], volume: "high" },
      { tag: "photographer", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "portrait", platform: ["instagram"], volume: "medium" },
      { tag: "landscape", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "camera", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "photoshoot", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "naturephotography", platform: ["instagram"], volume: "high" },
      { tag: "streetphotography", platform: ["instagram"], volume: "medium" },
      { tag: "travelphotography", platform: ["instagram"], volume: "high" },
      { tag: "photographytips", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "portraitphotography", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "dslr", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "sonyalpha", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "canon", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "lightroom", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "photographyideas", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "goldenhour", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "editing", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["camera", "lens", "edit", "composition", "exposure", "aperture", "shutter", "iso", "flash", "studio"],
  },
  music: {
    keywords: ["music", "song", "musician", "singer", "guitar", "piano", "producer", "beat", "rapper"],
    tags: [
      { tag: "music", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "musician", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "singer", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "song", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "guitar", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "piano", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "producer", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "beat", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "rapper", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "songwriter", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "musicproduction", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "vocals", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "hiphop", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "rock", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "jazz", platform: ["instagram", "youtube"], volume: "low" },
      { tag: "edm", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "livemusic", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "acoustic", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "musicvideo", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "cover", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
    ],
    expansions: ["audio", "melody", "rhythm", "harmony", "instrument", "band", "concert", "album", "single", "track"],
  },
  education: {
    keywords: ["education", "learning", "study", "school", "university", "course", "lecture", "tutorial", "learn"],
    tags: [
      { tag: "education", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "learning", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "study", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "studytips", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "university", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "student", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "course", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "tutorial", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "onlinelearning", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "studygram", platform: ["instagram"], volume: "high" },
      { tag: "studywithme", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "exams", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "math", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "science", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "history", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "languagelearning", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "productivity", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "motivation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "knowledge", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "skill", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["knowledge", "skill", "academic", "research", "teach", "class", "lesson", "curriculum", "degree", "certificate"],
  },
  business: {
    keywords: ["business", "entrepreneur", "marketing", "startup", "bisnis", "wirausaha", "branding", "digitalmarketing"],
    tags: [
      { tag: "business", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "entrepreneur", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "marketing", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "startup", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "bisnis", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "digitalmarketing", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "branding", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "success", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "motivation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "leadership", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "sales", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "ecommerce", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "socialmedia", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "wirausaha", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "entrepreneurindonesia", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "smallbusiness", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "onlineshop", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "businessowner", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "startupindonesia", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "tipsbisnis", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["strategy", "growth", "revenue", "profit", "innovation", "management", "networking", "pitch", "funding", "scale"],
  },
  beauty: {
    keywords: ["beauty", "makeup", "skincare", "cosmetic", "tutorialmakeup", "beautytips", "glowup"],
    tags: [
      { tag: "beauty", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "makeup", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "skincare", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "beautytips", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "makeuptutorial", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "skincareroutine", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "glowup", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "cosmetic", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "beautyblogger", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "makeupartist", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "nails", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "hair", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "selfcare", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "antiaging", platform: ["instagram", "youtube"], volume: "medium" },
      { tag: "eyeliner", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "lipstick", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "foundation", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "cleanser", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "serum", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "moisturizer", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
    ],
    expansions: ["cosmetic", "glow", "treatment", "organic", "natural", "veganbeauty", "crueltyfree", "facial", "bodycare", "fragrance"],
  },
  gaming: {
    keywords: ["gaming", "game", "gamer", "playstation", "xbox", "nintendo", "esport", "mobilelegend", "pubg", "valorant"],
    tags: [
      { tag: "gaming", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "gamer", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "game", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "playstation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "xbox", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "nintendo", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "esport", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "mobilelegend", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "pubg", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "valorant", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "fortnite", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "minecraft", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "callofduty", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "streamer", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "twitch", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "gameplay", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "gamingcommunity", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "indiegame", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "retrogaming", platform: ["instagram", "youtube"], volume: "low" },
      { tag: "pcgaming", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "rpg", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "fps", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "mlbb", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "freefire", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
    ],
    expansions: ["console", "multiplayer", "online", "stream", "competition", "level", "achievement", "quest", "battle", "tournament"],
  },
  health: {
    keywords: ["health", "healthy", "wellness", "mentalhealth", "healthylifestyle", "selfcare", "healing", "kesehatan"],
    tags: [
      { tag: "health", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "healthy", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "wellness", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "mentalhealth", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "healthylifestyle", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "selfcare", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "healing", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "mentalhealthmatters", platform: ["instagram", "tiktok"], volume: "high" },
      { tag: "selflove", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "mindfulness", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "meditation", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "wellbeing", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "kesehatan", platform: ["instagram", "tiktok", "youtube"], volume: "medium" },
      { tag: "hidupsehat", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "polahidupsehat", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "terapi", platform: ["instagram"], volume: "low" },
      { tag: "yoga", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "diet", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
      { tag: "immunity", platform: ["instagram", "tiktok"], volume: "medium" },
      { tag: "sleep", platform: ["instagram", "tiktok"], volume: "medium" },
    ],
    expansions: ["wellbeing", "fitness", "nutrition", "doctor", "medical", "therapy", "recovery", "balance", "organic", "natural"],
  },
};

// Generic high-volume hashtags (cross-niche)
export const genericHighVolumeTags: Omit<Hashtag, "score" | "category" | "competition">[] = [
  { tag: "viral", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
  { tag: "trending", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
  { tag: "explorepage", platform: ["instagram"], volume: "high" },
  { tag: "fyp", platform: ["tiktok"], volume: "high" },
  { tag: "foryoupage", platform: ["tiktok"], volume: "high" },
  { tag: "viralvideo", platform: ["tiktok", "youtube"], volume: "high" },
  { tag: "trend", platform: ["instagram", "tiktok"], volume: "high" },
  { tag: "contentcreator", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
  { tag: "socialmedia", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
  { tag: "viralcontent", platform: ["instagram", "tiktok"], volume: "high" },
  { tag: "trendingvideo", platform: ["tiktok", "youtube"], volume: "medium" },
  { tag: "reels", platform: ["instagram"], volume: "high" },
  { tag: "instadaily", platform: ["instagram"], volume: "high" },
  { tag: "tiktokindonesia", platform: ["tiktok"], volume: "high" },
  { tag: "youtube", platform: ["youtube"], volume: "high" },
  { tag: "subscribe", platform: ["youtube"], volume: "high" },
  { tag: "youtuber", platform: ["youtube"], volume: "high" },
  { tag: "content", platform: ["instagram", "tiktok", "youtube"], volume: "high" },
];

// Platform-specific tags
export const platformSpecificTags: Record<string, Omit<Hashtag, "score" | "category" | "competition">[]> = {
  youtube: [
    { tag: "youtube", platform: ["youtube"], volume: "high" },
    { tag: "subscribe", platform: ["youtube"], volume: "high" },
    { tag: "youtuber", platform: ["youtube"], volume: "high" },
    { tag: "video", platform: ["youtube"], volume: "high" },
    { tag: "vlog", platform: ["youtube"], volume: "high" },
    { tag: "tutorial", platform: ["youtube"], volume: "high" },
    { tag: "howto", platform: ["youtube"], volume: "high" },
    { tag: "review", platform: ["youtube"], volume: "high" },
    { tag: "challenge", platform: ["youtube"], volume: "high" },
    { tag: "reaction", platform: ["youtube"], volume: "high" },
    { tag: "unboxing", platform: ["youtube"], volume: "medium" },
    { tag: "tutorialyoutube", platform: ["youtube"], volume: "medium" },
    { tag: "newvideo", platform: ["youtube"], volume: "medium" },
    { tag: "subscribetomychannel", platform: ["youtube"], volume: "medium" },
    { tag: "creator", platform: ["youtube"], volume: "medium" },
  ],
  tiktok: [
    { tag: "fyp", platform: ["tiktok"], volume: "high" },
    { tag: "foryoupage", platform: ["tiktok"], volume: "high" },
    { tag: "tiktok", platform: ["tiktok"], volume: "high" },
    { tag: "viral", platform: ["tiktok"], volume: "high" },
    { tag: "trending", platform: ["tiktok"], volume: "high" },
    { tag: "tiktokindonesia", platform: ["tiktok"], volume: "high" },
    { tag: "fypシ", platform: ["tiktok"], volume: "high" },
    { tag: "duet", platform: ["tiktok"], volume: "medium" },
    { tag: "stitch", platform: ["tiktok"], volume: "medium" },
    { tag: "tiktokviral", platform: ["tiktok"], volume: "high" },
    { tag: "trendtiktok", platform: ["tiktok"], volume: "medium" },
    { tag: "foryou", platform: ["tiktok"], volume: "high" },
    { tag: "tiktokvideo", platform: ["tiktok"], volume: "medium" },
    { tag: "tiktokchallenge", platform: ["tiktok"], volume: "medium" },
    { tag: "tiktoktrend", platform: ["tiktok"], volume: "medium" },
  ],
  instagram: [
    { tag: "instagram", platform: ["instagram"], volume: "high" },
    { tag: "reels", platform: ["instagram"], volume: "high" },
    { tag: "explorepage", platform: ["instagram"], volume: "high" },
    { tag: "instagood", platform: ["instagram"], volume: "high" },
    { tag: "instadaily", platform: ["instagram"], volume: "high" },
    { tag: "photooftheday", platform: ["instagram"], volume: "high" },
    { tag: "likeforlike", platform: ["instagram"], volume: "medium" },
    { tag: "followforfollow", platform: ["instagram"], volume: "medium" },
    { tag: "instafashion", platform: ["instagram"], volume: "medium" },
    { tag: "instagramreels", platform: ["instagram"], volume: "high" },
    { tag: "reelsinstagram", platform: ["instagram"], volume: "high" },
    { tag: "instatips", platform: ["instagram"], volume: "medium" },
    { tag: "igreels", platform: ["instagram"], volume: "high" },
    { tag: "reel", platform: ["instagram"], volume: "high" },
    { tag: "instalike", platform: ["instagram"], volume: "medium" },
  ],
};

// Semantic expansion word pairs for generating related hashtags
export const semanticExpansions: Record<string, string[]> = {
  // Indonesian to English / related terms
  "lari": ["running", "jogging", "sprint", "marathon", "race"],
  "marathon": ["lari", "running", "halfmarathon", "ultramarathon", "race"],
  "investasi": ["investing", "saham", "stock", "finance", "wealth"],
  "saham": ["stock", "investasi", "trading", "market", "finance"],
  "makanan": ["food", "kuliner", "masakan", "recipe", "delicious"],
  "kuliner": ["food", "makanan", "travelfood", "streetfood", "foodie"],
  "kesehatan": ["health", "wellness", "sehat", "fitness", "selfcare"],
  "bisnis": ["business", "entrepreneur", "startup", "marketing", "branding"],
  "travel": ["wanderlust", "trip", "adventure", "explore", "vacation"],
  "fashion": ["style", "ootd", "outfit", "trend", "modestfashion"],
  "kecantikan": ["beauty", "makeup", "skincare", "glowup", "selfcare"],
  "game": ["gaming", "gamer", "esport", "playstation", "mobilelegend"],
  "olahraga": ["sport", "fitness", "gym", "workout", "exercise"],
  "musik": ["music", "song", "musician", "singer", "cover"],
  "teknologi": ["technology", "tech", "digital", "gadget", "innovation"],
  "pendidikan": ["education", "learning", "study", "knowledge", "skill"],
  "fotografi": ["photography", "photo", "camera", "portrait", "edit"],
  "bisnisonline": ["onlineshop", "ecommerce", "digitalmarketing", "startup", "socialmedia"],
  "motivasi": ["motivation", "inspiration", "success", "quotes", "mindset"],
  "islam": ["islamic", "muslim", "quran", "doa", "hijrah"],
};

export function findNiche(keyword: string): string | null {
  const lower = keyword.toLowerCase().trim();

  // Check direct keyword matches
  for (const [niche, entry] of Object.entries(nicheDatabase)) {
    if (entry.keywords.some(k => lower.includes(k) || k.includes(lower))) {
      return niche;
    }
  }

  // Check expansions
  for (const [niche, entry] of Object.entries(nicheDatabase)) {
    if (entry.expansions.some(e => lower.includes(e) || e.includes(lower))) {
      return niche;
    }
  }

  // Check semantic expansions
  for (const [word, expansions] of Object.entries(semanticExpansions)) {
    if (lower.includes(word) || expansions.some(e => lower.includes(e))) {
      // Map to appropriate niche
      if (["lari", "marathon", "olahraga", "running"].includes(word) || expansions.some(e => ["running", "fitness", "exercise"].includes(e))) return "fitness";
      if (["investasi", "saham", "bisnis", "bisnisonline"].includes(word)) return "investment";
      if (["makanan", "kuliner"].includes(word)) return "food";
      if (["kesehatan"].includes(word)) return "health";
      if (["travel"].includes(word)) return "travel";
      if (["fashion"].includes(word)) return "fashion";
      if (["kecantikan"].includes(word)) return "beauty";
      if (["game"].includes(word)) return "gaming";
      if (["musik"].includes(word)) return "music";
      if (["teknologi"].includes(word)) return "technology";
      if (["pendidikan"].includes(word)) return "education";
      if (["fotografi"].includes(word)) return "photography";
      if (["motivasi"].includes(word)) return "business";
    }
  }

  return null; // not found
}

export function getTagsByNiche(niche: string): Omit<Hashtag, "score" | "category" | "competition">[] {
  return nicheDatabase[niche]?.tags || [];
}

export function getExpansionsByNiche(niche: string): string[] {
  return nicheDatabase[niche]?.expansions || [];
}

export function getAllNiches(): string[] {
  return Object.keys(nicheDatabase);
}